[package]
name = "aws_auth"
version = "0.1.0"
authors = ["Pyry Kontio <pyry.kontio@drasa.eu>"]
edition = "2018"
description = "A crate for simple AWS authentication."
license = "MIT"

[dependencies]
ring = "0.16.9"
